version: "3"
services:
  postal:
    image: ghcr.io/postalserver/postal:latest
    ports:
      - "5000:5000" # Exposes Postal's web interface on host port 5000
    depends_on:
      - mariadb
    entrypoint: ["/docker-entrypoint.sh"]
    volumes:
      - "./docker/ci-config:/config"
    environment:
      POSTAL_SIGNING_KEY_PATH: /config/signing.key
      MAIN_DB_HOST: mariadb
      MAIN_DB_USERNAME: root
      MAIN_DB_PASSWORD: "" # Set a password if used
      MESSAGE_DB_HOST: mariadb
      MESSAGE_DB_USERNAME: root
      MESSAGE_DB_PASSWORD: "" # Set a password if used
      LOGGING_ENABLED: "false"
      RAILS_ENVIRONMENT: test
      RAILS_LOG_ENABLED: "false"
      WAIT_FOR_TIMEOUT: 90
      WAIT_FOR_TARGETS: |-
        mariadb:3306

  mariadb:
    image: mariadb:10.11 # Use a stable version for compatibility
    restart: always
    environment:
      MARIADB_DATABASE: postal
      MARIADB_USER: root
      MARIADB_PASSWORD: "" # Set a password if used
      MARIADB_ALLOW_EMPTY_PASSWORD: 'yes'
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
